### ISSUE TITLE
Segmentation fault when using `run`

### ISSUE THREAD

**Issue by samcv** [MoarVM/MoarVM#608] opened 2017-07-05 09:07 UTC
If you clone my module here: https://github.com/samcv/perl6-Font-QueryInfo

Then run the example `perl6 ./examples/QueryAllFonts.p6 /usr/share/fonts`.

Takes about 5 seconds to crash for me. It always crashes after the same amount of time +/- 0.2 seconds.

**Comment by jnthn** [comment] 2017-07-13 16:16
Was the same root cause as #612 which is now fixed.

**Closed by jnthn** 2017-07-13 16:16 UTC
