### ISSUE TITLE
MoarVM Panic when running S17-promise/lock-async-stress2.t

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#1237] opened 2020-02-12 15:48 UTC
Here's what it looks like:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-m -v
    This is Rakudo version 2020.01-155-g2e3c091 built on MoarVM version 2020.01.1-35-gecddb4d
    implementing Raku 6.d.
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ while MVM_SPESH_DISABLE=1 ./perl6-m -Ilib t/spec/S17-promise/lock-async-stress2.t; do :; done
    1..1
    ok 1 - Lock::Async provides mutual exclusion when doing +=
    1..1
    ok 1 - Lock::Async provides mutual exclusion when doing +=
    ... # sometimes quite many iterations are needed
    1..1
    MoarVM panic: Corrupt multi dispatch cache: cur_node != 0, re-check == (nil)

and here's the gdb perspective:

    1..1
    [New Thread 0x7ffff43db700 (LWP 15871)]
    [New Thread 0x7ffff3bda700 (LWP 15872)]
    [New Thread 0x7ffff28c3700 (LWP 15873)]
    [Switching to Thread 0x7ffff43db700 (LWP 15871)]
    
    Thread 2 "moar" hit Breakpoint 1, MVM_panic (exitCode=exitCode@entry=1, messageFormat=messageFormat@entry=0x7ffff769e980 "Corrupt multi dispatch cache: cur_node != 0, re-check == %p") at src/core/exceptions.c:833
    833	MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
    (gdb) bt 
    #0  MVM_panic (exitCode=exitCode@entry=1, messageFormat=messageFormat@entry=0x7ffff769e980 "Corrupt multi dispatch cache: cur_node != 0, re-check == %p") at src/core/exceptions.c:833
    #1  0x00007ffff75a31c8 in MVM_multi_cache_add (tc=0x44538a0, cache_obj=0x7fffec009f70, capture=<optimized out>, result=<optimized out>) at src/6model/reprs/MVMMultiCache.c:258
    #2  0x00007ffff7532987 in MVM_interp_run (tc=0x1, tc@entry=0x44538a0, initial_invoke=0x0, invoke_data=0x0, invoke_data@entry=0x44b4260) at src/core/interp.c:1538
    #3  0x00007ffff75488f6 in start_thread (data=0x44b4260) at src/core/threads.c:87
    #4  0x00007ffff6a4d6ba in start_thread (arg=0x7ffff43db700) at pthread_create.c:333
    #5  0x00007ffff707341d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
    (gdb) info threads
      Id   Target Id         Frame 
      1    Thread 0x7ffff7fdb700 (LWP 15870) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    * 2    Thread 0x7ffff43db700 (LWP 15871) "moar" MVM_panic (exitCode=exitCode@entry=1, messageFormat=messageFormat@entry=0x7ffff769e980 "Corrupt multi dispatch cache: cur_node != 0, re-check == %p") at src/core/exceptions.c:833
      3    Thread 0x7ffff3bda700 (LWP 15872) "moar" 0x00007ffff703830d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
      4    Thread 0x7ffff28c3700 (LWP 15873) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    (gdb) f 1
    #1  0x00007ffff75a31c8 in MVM_multi_cache_add (tc=0x44538a0, cache_obj=0x7fffec009f70, capture=<optimized out>, result=<optimized out>) at src/6model/reprs/MVMMultiCache.c:258
    258	            MVM_panic(1, "Corrupt multi dispatch cache: cur_node != 0, re-check == %p",
    (gdb) p MVM_dump_backtrace(tc)
       at gen/moar/BOOTSTRAP/v6c.nqp:2918  (/home/dogbert/repos/rakudo/blib/Perl6/BOOTSTRAP/v6c.moarvm:add_to_cache)
     from gen/moar/BOOTSTRAP/v6c.nqp:2929  (/home/dogbert/repos/rakudo/blib/Perl6/BOOTSTRAP/v6c.moarvm:)
     from SETTING::src/core.c/atomicops.pm6:21  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:cas)
     from SETTING::src/core.c/Lock/Async.pm6:72  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/Lock/Async.pm6:64  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:lock)
     from SETTING::src/core.c/Lock/Async.pm6:132  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:protect)
     from t/spec/S17-promise/lock-async-stress2.t:12  (<ephemeral file>:)
     from t/spec/S17-promise/lock-async-stress2.t:11  (<ephemeral file>:)
     from SETTING::src/core.c/Promise.pm6:267  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/ThreadPoolScheduler.pm6:896  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/ThreadPoolScheduler.pm6:248  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/ThreadPoolScheduler.pm6:239  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:run-one)
     from SETTING::src/core.c/ThreadPoolScheduler.pm6:281  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/Thread.pm6:54  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:THREAD-ENTRY)
    $1 = void
    (gdb) 

It should be noted that every crash, that I have seen, seems to involve 'cas'.

**Comment by Altai-man** [comment] 2020-02-13 13:22
Not a regression, see https://colabti.org/irclogger/irclogger_log/raku-dev?date=2020-02-13#l229

**Comment by dumarchie** [comment] 2020-12-12 08:56
I have some heavily parallel code (involving `cas`) that crashes with the following error more than once per 1000 runs:

```
MoarVM panic: Corrupt multi dispatch cache: cur_node != 0, re-check == 0000000000000000
```

It just happened with

>..\rakudo\install\bin\raku -v
Welcome to Rakudo(tm) v2020.10-247-g44cc88b54.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11-47-g1c7358004.

If someone tells me how to [stick a breakpoint in MVM_panic](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2020-02-13#l233) I may be able to tell what goes wrong here.

**Comment by MasterDuke17** [comment] 2020-12-12 09:29
gdb —args raku your_code.raku
Then inside gdb, ‘b MVM_panic’, then ‘r’. That should run until the panic happens. Then ‘bt’, and since MVM_panic doesn’t have a ‘tc’ parameter, ‘f 1’ and then ‘call MVM_dump_backtrace(tc)’. However, nine++ just made a bunch of NQP and Rakudo multithreading safety improvements and while your MoarVM is pretty new, you’re running an older Rakudo, so I’d also recommend upgrading them first.

**Comment by niner** [comment] 2020-12-12 09:32
> However, nine++ just made a
> bunch of NQP and Rakudo multithreading safety improvements
Not all of that is merged yet though:
https://github.com/Raku/nqp/pull/687

**Comment by dumarchie** [comment] 2020-12-12 09:34
Thank you, @MasterDuke17,

In case you would like to debug this yourself, checkout https://github.com/dumarchie/Collective and run `benchmark/stack.raku`. With just 4 `$*KERNEL.cpu-cores` my [latest commit](https://github.com/dumarchie/Collective/commit/71037a96e5c85f15b31a2a63e2c23749d953a701) crashes quite a lot on both my recent MinGW build and

>raku -v
This is Rakudo version 2020.05.1 built on MoarVM version 2020.05
implementing Raku 6.d.

**Comment by MasterDuke17** [comment] 2020-12-12 11:56
FWIW, I haven't been able to repro yet with:
```
raku -v
Welcome to Rakudo(tm) v2020.11-118-g9dbb52f9e.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11-85-g82a34e25a.
```

**Comment by dumarchie** [comment] 2020-12-12 12:19
Hmm, just in case you have exactly 2 CPU cores, try to run the script with options `--producers=1 --consumers=1`.

Also, in my experience the problem often starts occurring after running the script on a different Rakudo implementation.

In any case, if you're (still) not able to reproduce I'll run the script with `gdb` later this weekend.

**Comment by MasterDuke17** [comment] 2020-12-12 20:22
> Hmm, just in case you have exactly 2 CPU cores, try to run the script with options `--producers=1 --consumers=1`.

I have a 3700x, so 8 physical and `$*KERNEL.cpu-cores` reports 16. I tried changing the script to `4 * $*KERNEL.cpu-cores`, but that didn't make a difference.

**Comment by dumarchie** [comment] 2020-12-13 08:22
After a few runs on Rakudo version 2020.05.1 I got the following:

```
(gdb) r
Starting program: C:\rakudo\bin\raku.exe benchmark\stack.raku
[New Thread 12604.0xc64]
[New Thread 12604.0x3d54]
[New Thread 12604.0x37a4]
[New Thread 12604.0xc6c]
[New Thread 12604.0x2c9c]
[New Thread 12604.0x3890]
[New Thread 12604.0x17e0]
[New Thread 12604.0x3da4]
[New Thread 12604.0x3de4]
[New Thread 12604.0x1174]
Start producer 1
[New Thread 12604.0x166c]
Start consumer 1
[New Thread 12604.0x3de0]
Start consumer 2
[Switching to Thread 12604.0x166c]

Thread 11 hit Breakpoint 1, 0x0000000069bc6708 in MVM_panic () from C:\rakudo\bin\moar.dll
(gdb) bt
#0  0x0000000069bc6708 in MVM_panic () from C:\rakudo\bin\moar.dll
#1  0x0000000069c40313 in MVM_multi_cache_add () from C:\rakudo\bin\moar.dll
#2  0x00000000090c52b8 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) f 1
#1  0x0000000069c40313 in MVM_multi_cache_add () from C:\rakudo\bin\moar.dll
(gdb) call MVM_dump_backtrace(tc)
No symbol "tc" in current context.
```

I'm not sure how useful this output is, but I can try again given addtional/updated instructions.

**Comment by dumarchie** [comment] 2020-12-13 08:31
It took a bit longer to trigger the panic on Rakudo(tm) v2020.10-247-g44cc88b54, but the output looks very similar:

```
(gdb) r
Starting program: c:\raku\rakudo\install\bin\raku.exe benchmark\stack.raku
[New Thread 14832.0x3624]
[New Thread 14832.0x42c0]
[New Thread 14832.0x2184]
[New Thread 14832.0x3a8c]
[New Thread 14832.0x3ae8]
[New Thread 14832.0x13c8]
[New Thread 14832.0x2c88]
[New Thread 14832.0x950]
[New Thread 14832.0x19d0]
[New Thread 14832.0x4014]
Start producer 1
[New Thread 14832.0x15c0]
Start consumer 1
[New Thread 14832.0x3058]
Start consumer 2
[Switching to Thread 14832.0x15c0]

Thread 11 hit Breakpoint 1, 0x0000000069bc67a8 in MVM_panic () from c:\raku\rakudo\install\bin\moar.dll
(gdb) bt
#0  0x0000000069bc67a8 in MVM_panic () from c:\raku\rakudo\install\bin\moar.dll
#1  0x0000000069c43a73 in MVM_multi_cache_add () from c:\raku\rakudo\install\bin\moar.dll
#2  0x0000000009cf512b in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) f 1
#1  0x0000000069c43a73 in MVM_multi_cache_add () from c:\raku\rakudo\install\bin\moar.dll
(gdb) call MVM_dump_backtrace(tc)
No symbol "tc" in current context.
```

**Comment by MasterDuke17** [comment] 2020-12-13 08:47
﻿Are you building MoarVM with debugging? I.e., adding ‘—debug=3’ when running ‘perl Configure.pl’?

**Comment by dumarchie** [comment] 2020-12-13 08:50
No, but I will now :)

**Comment by MasterDuke17** [comment] 2020-12-13 08:51
Oh, and what about at HEAD? If you can’t reproduce it there maybe it has been fixed between v2020.10-247-g44cc88b54 and now.

**Comment by MasterDuke17** [comment] 2020-12-13 08:54
Also, running with `MVM_JIT_DISABLE=1` or `MVM_SPESH_DISABLE=1` can both help rule out the jit and/or spesh as the culprit and give cleaner backtraces.

**Comment by dumarchie** [comment] 2020-12-13 09:04
I'm now rebuilding Rakudo using `perl Configure.pl --gen-moar --gen-nqp --backends=moar --moar-option="--debug=3"`. After that I will run `gdb` again and see if I can still trigger the panic. If so, I'll do it again with jit and spesh disabled.

**Comment by MasterDuke17** [comment] 2020-12-13 09:12
Cool. I don't remember if you've been in the #moarvm IRC channel, but that's also a good place for slightly more interactive help.

**Comment by dumarchie** [comment] 2020-12-13 16:12
Okay, on the fourth run with

>install\bin\raku -v
Welcome to Rakudo(tm) v2020.10-275-gc63f078a2.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11-85-g82a34e25a.

I got

```
(gdb) r
Starting program: c:\raku\rakudo\install\bin\raku.exe benchmark\stack.raku
[New Thread 24848.0x5f88]
[New Thread 24848.0x6120]
[New Thread 24848.0x3efc]
[New Thread 24848.0x56a4]
[New Thread 24848.0x5900]
[New Thread 24848.0x6104]
[New Thread 24848.0x6114]
[New Thread 24848.0x64cc]
[New Thread 24848.0x679c]
[New Thread 24848.0x659c]
Start producer 1
[New Thread 24848.0x60fc]
Start consumer 1
[New Thread 24848.0x5dd8]
Start consumer 2
[Switching to Thread 24848.0x60fc]

Thread 11 hit Breakpoint 1, MVM_panic (exitCode=1,
    messageFormat=0x69e44f18 <MVMDLLSym_this_repr+632> "Corrupt multi dispatch cache: cur_node != 0, re-check == %p")
    at src\core\exceptions.c:844
844     MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
(gdb) bt
#0  MVM_panic (exitCode=1,
    messageFormat=0x69e44f18 <MVMDLLSym_this_repr+632> "Corrupt multi dispatch cache: cur_node != 0, re-check == %p")
    at src\core\exceptions.c:844
#1  0x0000000069c45653 in MVM_multi_cache_add (tc=0xa650400, cache_obj=<optimized out>, capture=<optimized out>,
    result=<optimized out>) at src\6model\reprs\MVMMultiCache.c:258
#2  0x0000000009e3512b in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) f 1
#1  0x0000000069c45653 in MVM_multi_cache_add (tc=0xa650400, cache_obj=<optimized out>, capture=<optimized out>,
    result=<optimized out>) at src\6model\reprs\MVMMultiCache.c:258
258                 MVM_panic(1, "Corrupt multi dispatch cache: cur_node != 0, re-check == %p",
(gdb) call MVM_dump_backtrace(tc)
   at gen\moar\BOOTSTRAP\v6c.nqp:2612  (C:\raku\rakudo\install\share\perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:)
 from SETTING::src/core.c/atomicops.pm6:9  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:prefix:<⚛>)
 from C:\raku\Collective\lib\Collective\Stack.rakumod (Collective::Stack):63  (C:\raku\Collective\lib\.precomp\1978FD4B0C781B715F93AA2DD44DB1671810A17F\84\84EFF517B87E2DAC77F55707D53CFD8B5CE5222B:extract)
 from C:\raku\Collective\lib\Collective\Stack.rakumod (Collective::Stack):53  (C:\raku\Collective\lib\.precomp\1978FD4B0C781B715F93AA2DD44DB1671810A17F\84\84EFF517B87E2DAC77F55707D53CFD8B5CE5222B:pop)
 from benchmark\stack.raku:70  (<ephemeral file>:)
 from benchmark\stack.raku:80  (<ephemeral file>:timer)
 from benchmark\stack.raku:120  (<ephemeral file>:)
 from SETTING::src/core.c/Promise.pm6:267  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:899  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:248  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:242  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:239  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:run-one)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:281  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Thread.pm6:54  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:THREAD-ENTRY)
```

**Comment by dumarchie** [comment] 2020-12-13 16:47
With both  `MVM_JIT_DISABLE=1` and `MVM_SPESH_DISABLE=1` it took some more runs, but in the end I got:

```
(gdb) r
Starting program: c:\raku\rakudo\install\bin\raku.exe benchmark\stack.raku
[New Thread 22532.0x5f24]
[New Thread 22532.0x66e8]
[New Thread 22532.0x6008]
[New Thread 22532.0x5c94]
[New Thread 22532.0x1678]
[New Thread 22532.0x5cf4]
[New Thread 22532.0x593c]
[New Thread 22532.0x5b10]
[New Thread 22532.0x664c]
Start producer 1
[New Thread 22532.0x5e88]
Start consumer 1
[New Thread 22532.0x3d8c]
Start consumer 2
[Switching to Thread 22532.0x5e88]

Thread 10 hit Breakpoint 1, MVM_panic (exitCode=1,
    messageFormat=0x69e44f18 <MVMDLLSym_this_repr+632> "Corrupt multi dispatch cache: cur_node != 0, re-check == %p")
    at src\core\exceptions.c:844
844     MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
(gdb) bt
#0  MVM_panic (exitCode=1,
    messageFormat=0x69e44f18 <MVMDLLSym_this_repr+632> "Corrupt multi dispatch cache: cur_node != 0, re-check == %p")
    at src\core\exceptions.c:844
#1  0x0000000069c45653 in MVM_multi_cache_add (tc=0xa189350, cache_obj=<optimized out>, capture=<optimized out>,
    result=<optimized out>) at src\6model\reprs\MVMMultiCache.c:258
#2  0x0000000069bd9389 in MVM_interp_run (tc=0x1, tc@entry=0xa189350, initial_invoke=0x0, invoke_data=0x0,
    invoke_data@entry=0x8e7e4d0, outer_runloop=0xbe730, outer_runloop@entry=0x0) at src\core\interp.c:1536
#3  0x0000000069bf236f in start_thread (data=0x8e7e4d0) at src\core\threads.c:91
#4  0x0000000069d39901 in uv.thread_start () at src/6model/6model.h:725
#5  0x00007ffb0010af5a in msvcrt!_beginthreadex () from C:\WINDOWS\System32\msvcrt.dll
#6  0x00007ffb0010b02c in msvcrt!_endthreadex () from C:\WINDOWS\System32\msvcrt.dll
#7  0x00007ffb00187034 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#8  0x00007ffb00a1d0d1 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#9  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) f 1
#1  0x0000000069c45653 in MVM_multi_cache_add (tc=0xa189350, cache_obj=<optimized out>, capture=<optimized out>,
    result=<optimized out>) at src\6model\reprs\MVMMultiCache.c:258
258                 MVM_panic(1, "Corrupt multi dispatch cache: cur_node != 0, re-check == %p",
(gdb) call MVM_dump_backtrace(tc)
   at gen\moar\BOOTSTRAP\v6c.nqp:2894  (C:\raku\rakudo\install\share\perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:add_to_cache)
 from gen\moar\BOOTSTRAP\v6c.nqp:2905  (C:\raku\rakudo\install\share\perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:)
 from SETTING::src/core.c/atomicops.pm6:9  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:prefix:<⚛>)
 from C:\raku\Collective\lib\Collective\Stack.rakumod (Collective::Stack):63  (C:\raku\Collective\lib\.precomp\1978FD4B0C781B715F93AA2DD44DB1671810A17F\84\84EFF517B87E2DAC77F55707D53CFD8B5CE5222B:extract)
 from C:\raku\Collective\lib\Collective\Stack.rakumod (Collective::Stack):53  (C:\raku\Collective\lib\.precomp\1978FD4B0C781B715F93AA2DD44DB1671810A17F\84\84EFF517B87E2DAC77F55707D53CFD8B5CE5222B:pop)
 from benchmark\stack.raku:70  (<ephemeral file>:)
 from benchmark\stack.raku:80  (<ephemeral file>:timer)
 from benchmark\stack.raku:120  (<ephemeral file>:)
 from SETTING::src/core.c/Promise.pm6:267  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:899  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:248  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:242  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:239  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:run-one)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:281  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Thread.pm6:54  (C:\raku\rakudo\install\share\perl6\runtime/CORE.c.setting.moarvm:THREAD-ENTRY)
```

**Comment by dumarchie** [comment] 2020-12-14 06:24
I just noticed that the panic only happens after a `Switching to Thread`. For comparison, here's the output of a successful run:

```
(gdb) r
Starting program: c:\raku\rakudo\install\bin\raku.exe benchmark\stack.raku
[New Thread 1812.0x6450]
[New Thread 1812.0x5f24]
[New Thread 1812.0x5804]
[New Thread 1812.0x6ee4]
[New Thread 1812.0x68a4]
[New Thread 1812.0x6d54]
[New Thread 1812.0x6e88]
[New Thread 1812.0x6d44]
[New Thread 1812.0x6c3c]
Start producer 1
[New Thread 1812.0x6e84]
Start consumer 1
[New Thread 1812.0x624]
Start consumer 2
Consumer 1 needed 3.049 seconds and 153911 calls to pop 150000 values
Producer 1 needed 3.173 seconds and 300000 calls to push 300000 values
Consumer 2 needed 3.122 seconds and 153813 calls to pop 150000 values
Total time spent: 3.191 seconds
Top value: Nil
[Thread 1812.0x6d44 exited with code 0]
[Thread 1812.0x6c3c exited with code 0]
[Thread 1812.0x6d54 exited with code 0]
[Thread 1812.0x6e88 exited with code 0]
[Thread 1812.0x624 exited with code 0]
[Thread 1812.0x68a4 exited with code 0]
[Thread 1812.0x5804 exited with code 0]
[Thread 1812.0x5f24 exited with code 0]
[Thread 1812.0x6e84 exited with code 0]
[Thread 1812.0x6ee4 exited with code 0]
[Inferior 1 (process 1812) exited normally]
```

Could the multi dispatch cache be corrupted by a data race?

**Comment by dumarchie** [comment] 2020-12-14 08:33
I suspect the data race happens in https://github.com/MoarVM/MoarVM/blob/82a34e25a8f66847a1d895214488264618f4dd82/src/6model/reprs/MVMMultiCache.c#L160-L164

It would explain why it is so hard to trigger the panic.

**Closed** 2021-04-04 09:36 UTC
