### ISSUE TITLE
GC fail while building panda

### ISSUE THREAD

**Issue by gfldex** [MoarVM/MoarVM#352] opened 2016-03-29 11:32 UTC
see: https://travis-ci.org/perl6/doc/builds/119216311

==> Installing File::Find

Internal error: zeroed target thread ID in work pass

The spawned process exited unsuccessfully (exit code: 17)

  in sub MAIN at bootstrap.pl line 66

  in block <unit> at bootstrap.pl line 8

**Comment by jnthn** [comment] 2017-07-14 16:07
It's been a good while since this was filed, and we've fixed dozens of things that could have been to blame in the meantime; Panda is also no longer maintained, but zef certainly seems to install it fine. Closing as the issue was likely fixed long ago, and I can't reproduce it with current tooling.

**Closed by jnthn** 2017-07-14 16:07 UTC
